### ISSUE TITLE
HTTPError: Forbidden errros 

### ISSUE THREAD

**Issue by rootxad** [maple3142/GDIndex#184]
# Bug Description / 問題描述

The index sometime throughs an error:

`"HTTPError: Forbidden\n    at responseErrorThrower (worker.js:185:26)\n    at async GoogleDrive.existsInParent (worker.js:499:20)\n    at async onGet (worker.js:589:31)\n    at async handleRequest (worker.js:769:42)"`

This error is been reported before, but as per lack of information and not using the issue template the author closed the report. I checked and the installation and config are done properly. I also think it is not because of the bandwidth limit as if I refresh the URL some time it succeeds. 

# Environment / 環境

* Browser version / 瀏覽器版本: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36Chrome 88 on Linux
* OS version / 作業系統版本: Ubuntu 18.04

**Comment by rootxad** [comment]
Or if we can return a new response if this error occurs, as if request returns status 500, return a new response with Unknown error and hide this error.

`"HTTPError: Forbidden\n at responseErrorThrower (worker.js:185:26)\n at async GoogleDrive.existsInParent (worker.js:499:20)\n at async onGet (worker.js:589:31)\n at async handleRequest (worker.js:769:42)"`

**Comment by maple3142** [comment]
Can't reproduct, maybe it has some problem with your Google account, consider trying it on other Google account

**Comment by devcrono** [comment]
I'm using services account, in your script and time or other he gives this error message

"HTTPError: Forbidden\n    at responseErrorThrower (worker.js:192:26)\n    at async onGet (worker.js:2762:19)\n    at async handleRequest (worker.js:2975:42)"

I attached the cod. for conference
[teste.txt](https://github.com/maple3142/GDIndex/files/5939734/teste.txt)

**Comment by njzjz** [comment]
I got another error...
```
"HTTPError: Conflict\n    at responseErrorThrower (worker.js:177:26)\n    at async GoogleDrive.initializeClient (worker.js:2523:22)\n    at async GoogleDrive.listFolder (worker.js:2585:7)\n    at async handleRequest (worker.js:2908:11)"
```
----
UPDATE: I resolved this problem. It's a bug of CloudFlare Workers.

**Comment by rootxad** [comment]
> UPDATE: I solved this problem. It's a bug of CloudFlare Workers.

Would you like to share the bug ?? or how you solved it ??

**Comment by njzjz** [comment]
> > UPDATE: I solved this problem. It's a bug of CloudFlare Workers.
> 
> Would you like to share the bug ?? or how you solved it ??

cloudflare resolved it, but not me... I don't think your bug is the same as mine, but you can consider if it is a cloudflare's network issue.

**Comment by Monster-ZeroX** [comment]
How Can I Fix This
