### ISSUE TITLE
团队盘下载和预览问题

### ISSUE THREAD

**Issue by sunnynctu** [maple3142/GDIndex#191]
# Bug Description / 問題描述  团队盘下载和预览问题

<>挂载成功后显示个人盘和团队盘，个人盘一切正常，团队盘无法下载或者预览
直接点击预览提示
`HTTPError: Forbidden\n    at responseErrorThrower (worker.js:179:26)\n    at async onGet (worker.js:2749:19)\n    at async handleRequest (worker.js:2942:42)`
点击下载IDM提示
`HTTP /1.1 500 Internal Server Error`
Chrome直接下载提示都是`文件同名.json`文件，而且下载失败
用自动和手动两种方法都部署了，结果完全一样

# Environment / 環境

* Browser version / 瀏覽器版本: Google Chrome 版本 89.0.4389.90
* OS version / 作業系統版本: Microsoft Windows 10 19042.867

**Comment by maple3142** [comment]
我沒這個問題

**Comment by yinguo520** [comment]
一样的问题。

**Comment by sunnynctu** [comment]
> 一样的问题。

我的团队盘在官网可以上传但不能下载和预览，15G个人盘一切正常，看来是被谷歌风控了。

**Comment by patrick-tssn** [comment]
请问lz解决了嘛？

**Comment by sunnynctu** [comment]
> 请问lz解决了嘛？

下载超限应该是被风控了，无法解决

**Comment by sunnynctu** [comment]
> 请问lz解决了嘛？

在gd官网都不能预览或者下载，彻底凉凉
