### ISSUE TITLE
Bug Report for Lite Version and facing error when Index is listing files

### ISSUE THREAD

**Issue by rootxad** [maple3142/GDIndex#196]
# Bug Description / 問題描述

`"TypeError: Cannot destructure property 'files' of '(intermediate value)' as it is null.\n    at handleRequest (worker.js:2910:9)"`

`"HTTPError: Forbidden\n    at responseErrorThrower (worker.js:179:26)\n    at async GoogleDrive.listFolder (worker.js:2613:22)\n    at async handleRequest (worker.js:2911:11)"`

This both results in failed download and index preview.

I tried other GDIndex repo available on Github, they seem to work fine.
Which one i tried ??

https://github.com/ParveenBhadooOfficial/Google-Drive-Index

# What Debugging, i have tried and didn't worked:

> Performed a fresh installation.
> Changed the drive root ids and refresh token.

# Environment / 環境

* Browser version / 瀏覽器版本: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36
* OS version / 作業系統版本: Ubuntu 20.04

**Comment by rootxad** [comment]
I also tested the demo link provided: 
https://gdindex-demo.maple3142.workers.dev/

Under 10 refresh you will face these errors.

**Comment by rootxad** [comment]
Create your own client_id, client_secret, and refresh token.
Fixes the limits.
