### ISSUE TITLE
HELP!HELP!!HELP!!!

### ISSUE THREAD

**Issue by miuexy** [maple3142/GDIndex#216]
# Bug Description / 問題描述
"TypeError: Cannot read properties of undefined (reading 'split')\n    at handleRequest (worker.js:2902:39)\n    at worker.js:2961:21"

Deploy an error

# Environment / 環境

* Browser version / 瀏覽器版本:
*firefox
* OS version / 作業系統版本:win10

**Comment by imjiaoyuan** [comment]
I also encountered the same problem, my computer is Windows 10 system and the latest version of chrome browser

**Comment by Amadeus-AI** [comment]
@maple3142
I also encountered this issue.

**Comment by Anshbloger** [comment]
"TypeError: Cannot read properties of undefined (reading 'split')\n    at handleRequest (worker.js:3153:39)\n    at worker.js:3212:21\n    HELP CODE ERROR BRO
