### ISSUE TITLE
"TypeError: Cannot read properties of undefined (reading 'split')\n    at handleRequest (worker.js:2902:39)\n    at worker.js:2961:21"

### ISSUE THREAD

**Issue by Fashionedgroot** [maple3142/GDIndex#219]
after pasting the code i got from https://gdindex-code-builder.maple3142.net/ this site in cloudlfare workers i am getting the following error please help.
"TypeError: Cannot read properties of undefined (reading 'split')\n    at handleRequest (worker.js:2902:39)\n    at worker.js:2961:21"

**Comment by Fashionedgroot** [comment]
"TypeError: Cannot read properties of undefined (reading 'split')\n    at handleRequest (worker.js:3253:39)\n    at worker.js:3314:21\n    at __facade_sw_fetch__ (worker.js:171:31)\n    at __facade_invokeChain__ (worker.js:25:12)\n    at Object.next (worker.js:22:16)\n    at jsonError (worker.js:231:34)\n    at __facade_invokeChain__ (worker.js:25:12)\n    at Object.next (worker.js:22:16)\n    at scheduled (worker.js:213:26)\n    at __facade_invokeChain__ (worker.js:25:12)"
these are some more issues i encountered
please help me

**Comment by Misaka13514** [comment]
Try to [use wrangler to deploy](https://developers.cloudflare.com/workers/wrangler/commands/#deploy) and set flag [--compatibility-date 2021-11-10](https://developers.cloudflare.com/workers/configuration/compatibility-dates/)
